name: test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  FOUNDRY_PROFILE: ci
  ETH_RPC_URL: https://rpc-beta1.turablockchain.com

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
      - name: Run Forge tests
        run: |
          forge test -vvv
